# version: '3'
# services:
#   mongo:
#     image: mongo:3.6
#   web:
#     build: .
#     ports:
#      - "8080:8080"
#     environment:
#      - MONGODB_URI=mongodb://mongo:27017/test 
#     links:
#      - mongo 
#     depends_on: 
#      - mongo 
#     volumes:
#      - .:/starter
#      - /starter/node_modules


version: '3'
services:
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always