name: CI/CD
on:
  push:
    branches:
      - master
      - production
env:
  REVIEWERS: pajacobs17
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  AWS_SECRET_REGION: us-east-1

jobs:
  environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ format('{0}{1}', steps.staging.outputs.environment, steps.production.outputs.environment) }}
    steps:
      - name: Set staging environment
        id: staging
        if: github.ref == 'refs/heads/master'
        run: echo "::set-output name=environment::staging"

      - name: Set production environment
        id: production
        if: github.ref == 'refs/heads/production'
        run: echo "::set-output name=environment::production"
  deploy:
    needs:
      - environment
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ needs.environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy staging
        if: ${{ env.ENVIRONMENT == 'staging' }}
        run: |
          echo 

  pr:
    needs:
      - environment
      - deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ needs.environment.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull request to production
        if: ${{ env.ENVIRONMENT == 'staging' }}
        run: hub pull-request -b production -h master -a ${{ github.event.pusher.name }} -m "Push to Production" -r $REVIEWERS || exit 0
