name: Create a pull request
on:
  push:
    branches-ignore:
      - master
      - production
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get commit message
        run: |
          echo "COMMIT_MSG=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

      - name: Create PR
        run: |
          hub pull-request --draft -b master -h ${{ github.event.ref }} -a ${{ github.event.pusher.name }} -m "$COMMIT_MSG" || exit 0
